<?php

$date = date('Y-m-d H:i:s');

return [
    array('category_id' => '1','name' => 'Home','title' => 'Home','excerpt' => 'home excerpt...','content' => 'content home...','active_key' => 'home','third_party_mapping_key' => NULL,'b2b_mapping' => NULL,'is_external' => '0','link_relation' => NULL,'target' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_robots' => NULL,'meta_canonical' => NULL,'created_at' => $date,'updated_at' => $date,'deleted_at' => NULL),
    array('category_id' => '2','name' => 'Blog','title' => 'Find our latest blog','excerpt' => NULL,'content' => NULL,'active_key' => 'blog','third_party_mapping_key' => NULL,'b2b_mapping' => NULL,'is_external' => '0','link_relation' => 'alternate','target' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_robots' => NULL,'meta_canonical' => NULL,'created_at' => $date,'updated_at' => $date,'deleted_at' => NULL),
    array('category_id' => '3','name' => 'Login','title' => 'Login','excerpt' => NULL,'content' => NULL,'active_key' => 'login','third_party_mapping_key' => NULL,'b2b_mapping' => NULL,'is_external' => '0','link_relation' => NULL,'target' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_robots' => NULL,'meta_canonical' => NULL,'created_at' => $date,'updated_at' => $date,'deleted_at' => NULL),
    array('category_id' => '4','name' => 'Register','title' => 'Register','excerpt' => NULL,'content' => NULL,'active_key' => 'register','third_party_mapping_key' => NULL,'b2b_mapping' => NULL,'is_external' => '0','link_relation' => NULL,'target' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_robots' => NULL,'meta_canonical' => NULL,'created_at' => $date,'updated_at' => $date,'deleted_at' => NULL),
    array('category_id' => '5','name' => 'Reset Password','title' => 'Reset Password','excerpt' => NULL,'content' => NULL,'active_key' => 'password','third_party_mapping_key' => NULL,'b2b_mapping' => NULL,'is_external' => '0','link_relation' => NULL,'target' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_robots' => NULL,'meta_canonical' => NULL,'created_at' => $date,'updated_at' => $date,'deleted_at' => NULL),
    array('category_id' => '6','name' => 'Example','title' => 'Example','excerpt' => NULL,'content' => NULL,'active_key' => 'example','third_party_mapping_key' => NULL,'b2b_mapping' => NULL,'is_external' => '0','link_relation' => NULL,'target' => NULL,'meta_title' => 'Example','meta_keywords' => NULL,'meta_description' => NULL,'meta_robots' => NULL,'meta_canonical' => NULL,'created_at' => $date,'updated_at' => $date,'deleted_at' => NULL),
    array('category_id' => '7','name' => 'Profile','title' => 'Profile','excerpt' => NULL,'content' => NULL,'active_key' => 'Profile','third_party_mapping_key' => NULL,'b2b_mapping' => NULL,'is_external' => '0','link_relation' => 'alternate','target' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_robots' => NULL,'meta_canonical' => NULL,'created_at' => $date,'updated_at' => $date,'deleted_at' => NULL),
    array('category_id' => '8','name' => 'Contact','title' => 'Contact','excerpt' => NULL,'content' => NULL,'active_key' => 'contact','third_party_mapping_key' => NULL,'b2b_mapping' => NULL,'is_external' => '0','link_relation' => 'alternate','target' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_robots' => NULL,'meta_canonical' => NULL,'created_at' => $date,'updated_at' => $date,'deleted_at' => NULL),
    array('category_id' => '9','name' => 'Support','title' => 'Support','excerpt' => NULL,'content' => NULL,'active_key' => 'support','third_party_mapping_key' => NULL,'b2b_mapping' => NULL,'is_external' => '0','link_relation' => NULL,'target' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_robots' => NULL,'meta_canonical' => NULL,'created_at' => $date,'updated_at' => $date,'deleted_at' => NULL)
];
