<?php

$date = date('Y-m-d H:i:s');

return [
    array('category_id' => '1','name' => 'होम','title' => 'होम','excerpt' => 'होम अंश...','content' => 'होम सामग्री...','active_key' => 'home','third_party_mapping_key' => NULL,'b2b_mapping' => NULL,'is_external' => '0','link_relation' => NULL,'target' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_robots' => NULL,'meta_canonical' => NULL,'created_at' => $date,'updated_at' => $date,'deleted_at' => NULL),
    array('category_id' => '2','name' => 'ब्लॉग','title' => 'हमारे नवीनतम ब्लॉग खोजें','excerpt' => NULL,'content' => NULL,'active_key' => 'blog','third_party_mapping_key' => NULL,'b2b_mapping' => NULL,'is_external' => '0','link_relation' => 'alternate','target' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_robots' => NULL,'meta_canonical' => NULL,'created_at' => $date,'updated_at' => $date,'deleted_at' => NULL),
    array('category_id' => '3','name' => 'लॉगिन','title' => 'लॉगिन','excerpt' => NULL,'content' => NULL,'active_key' => 'login','third_party_mapping_key' => NULL,'b2b_mapping' => NULL,'is_external' => '0','link_relation' => NULL,'target' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_robots' => NULL,'meta_canonical' => NULL,'created_at' => $date,'updated_at' => $date,'deleted_at' => NULL),
    array('category_id' => '4','name' => 'रजिस्टर','title' => 'रजिस्टर','excerpt' => NULL,'content' => NULL,'active_key' => 'register','third_party_mapping_key' => NULL,'b2b_mapping' => NULL,'is_external' => '0','link_relation' => NULL,'target' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_robots' => NULL,'meta_canonical' => NULL,'created_at' => $date,'updated_at' => $date,'deleted_at' => NULL),
    array('category_id' => '5','name' => 'पासवर्ड रीसेट करें','title' => 'पासवर्ड रीसेट करें','excerpt' => NULL,'content' => NULL,'active_key' => 'password','third_party_mapping_key' => NULL,'b2b_mapping' => NULL,'is_external' => '0','link_relation' => NULL,'target' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_robots' => NULL,'meta_canonical' => NULL,'created_at' => $date,'updated_at' => $date,'deleted_at' => NULL),
    array('category_id' => '6','name' => 'उदाहरण','title' => 'उदाहरण','excerpt' => NULL,'content' => NULL,'active_key' => 'example','third_party_mapping_key' => NULL,'b2b_mapping' => NULL,'is_external' => '0','link_relation' => NULL,'target' => NULL,'meta_title' => 'उदाहरण','meta_keywords' => NULL,'meta_description' => NULL,'meta_robots' => NULL,'meta_canonical' => NULL,'created_at' => $date,'updated_at' => $date,'deleted_at' => NULL),
    array('category_id' => '7','name' => 'प्रोफ़ाइल','title' => 'प्रोफ़ाइल','excerpt' => NULL,'content' => NULL,'active_key' => 'Profile','third_party_mapping_key' => NULL,'b2b_mapping' => NULL,'is_external' => '0','link_relation' => 'alternate','target' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_robots' => NULL,'meta_canonical' => NULL,'created_at' => $date,'updated_at' => $date,'deleted_at' => NULL),
    array('category_id' => '8','name' => 'संपर्क करें','title' => 'संपर्क करें','excerpt' => NULL,'content' => NULL,'active_key' => 'contact','third_party_mapping_key' => NULL,'b2b_mapping' => NULL,'is_external' => '0','link_relation' => 'alternate','target' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_robots' => NULL,'meta_canonical' => NULL,'created_at' => $date,'updated_at' => $date,'deleted_at' => NULL),
    array('category_id' => '9','name' => 'सहायता','title' => 'सहायता','excerpt' => NULL,'content' => NULL,'active_key' => 'support','third_party_mapping_key' => NULL,'b2b_mapping' => NULL,'is_external' => '0','link_relation' => NULL,'target' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_robots' => NULL,'meta_canonical' => NULL,'created_at' => $date,'updated_at' => $date,'deleted_at' => NULL)
];
