<?php

return [
    'namespace' => 'HashtagCms\\',
    'context' => env('CONTEXT', 'hashtagcms'),
    'info' => [
        'view_folder' => 'hashtagcms::fe',
        'site_name' => 'Hashtag CMS',
        'base_path' => '',
        'theme' => 'fe.default',
        /***
         * In case you want to set up a different CDN
         * for the different site
         */
        /*'assets_path'=>array("dev.hashtagcms.com"=>array('base_url'=>env('ASSET_URL', 'https://images.hashtagcms.org/media'),
                                    'base_path'=>'/assets/hashtagcms/fe',
                                    'js'=>'js', 'css'=>'css', 'image'=>'img')
        ),*/
        'assets_path' => [
            'base_url' => env('ASSET_URL', ''),
            'base_path' => '/assets/hashtagcms/fe',
            'js' => 'js',
            'css' => 'css',
            'image' => 'img'
        ],
        'media_path' => '/storage/media',
        'records_per_page' => 20,
    ],
    'media' => [
        'upload_path' => 'public/media',
        'http_path' => '/storage/media',
    ],
    'message' => [
        'zeroModuleSelected' => "<div style='margin: 100px; text-align: center; font-size: 70px; color:mediumvioletred'>There is no module assigned for this category</div>",
    ],
    'redirect_with_message_design' => [
        'css_success' => 'alert alert-primary mb-0 appear',
        'css_error' => 'alert-danger alert mb-0 appear',
        'css_error_close_button' => 'fa fa-times',
        'error_close_text' => '',
    ],
    'blog_per_page' => 10,
    'more_categories_on_blog_listing' => [], //array("support")

    /**
     * This is necessary to run the same site on multiple domains.
     * When you want to run it via an external API, you need to have
     * the domain and context key combination here to operate the site.
     * Think of it as a virtual host. 
     * For example if you have a site with context 'htcms' and you want to run it on dev.hashtagcms.com
     * then you need to add it here as 'dev.hashtagcms.com' => 'htcms'.
     */
    'domains' => [
        'dev.hashtagcms.com' => env('CONTEXT', 'htcms')
    ],
    'api_secrets' => [
        /**
         * Do not forget the change this key when you go in production
         * This is a combination of context and random key.
         * will be used in api ie /api/hashtagcms/public/configs/v1/site-configs?site=htcmsctx&api_secret=61d2aeb489bb8df385
         * x-api-secret as header will be set with the same value
         * This is not the same as api_secret. It's random key generated by you. Must change it. 
         */
        'procms' => env('API_SECRET', '61c58507bbac1'),
    ],
    /**
     * Additional middleware to be applied to all HashtagCMS routes
     * Add middleware names that you want to apply to all HashtagCMS routes
     * Example: ['auth', 'invite']
     */
    'additional_middleware' => [],
    /**
     * External API Configuration
     */
    'enable_external_api' => env('HASHTAGCMS_ENABLE_EXTERNAL_API', false),
    'external_api_cache_prefix' => env('HASHTAGCMS_EXTERNAL_API_CACHE_PREFIX', 'api_'),
    'external_api_base_url' => env('HASHTAGCMS_EXTERNAL_API_BASE_URL', env('APP_URL')),
    'config_api' => env('HASHTAGCMS_CONFIG_API', env('HASHTAGCMS_EXTERNAL_API_BASE_URL') . '/api/hashtagcms/public/configs/v1/site-configs'),
    'data_api' => env('HASHTAGCMS_DATA_API', env('HASHTAGCMS_EXTERNAL_API_BASE_URL') . '/api/hashtagcms/public/sites/v1/load-data'),
    'login_api' => env('HASHTAGCMS_LOGIN_API', env('HASHTAGCMS_EXTERNAL_API_BASE_URL') . '/api/hashtagcms/public/sites/v1/login'),
    'logout_api' => env('HASHTAGCMS_LOGOUT_API', env('HASHTAGCMS_EXTERNAL_API_BASE_URL') . '/api/hashtagcms/public/user/v1/logout'),
    'user_me_api' => env('HASHTAGCMS_USER_ME_API', env('HASHTAGCMS_EXTERNAL_API_BASE_URL') . '/api/hashtagcms/user/v1/me'),
    'user_profile_update_api' => env('HASHTAGCMS_USER_PROFILE_UPDATE_API', env('HASHTAGCMS_EXTERNAL_API_BASE_URL') . '/api/hashtagcms/user/v1/profile'),
    'publish_api' => env('HASHTAGCMS_PUBLISH_API', env('HASHTAGCMS_EXTERNAL_API_BASE_URL') . '/api/hashtagcms/public/kpi/v1/publish'),
    'contact_api' => env('HASHTAGCMS_CONTACT_API', env('HASHTAGCMS_EXTERNAL_API_BASE_URL') . '/api/hashtagcms/public/common/v1/contact'),
    'subscribe_api' => env('HASHTAGCMS_SUBSCRIBE_API', env('HASHTAGCMS_EXTERNAL_API_BASE_URL') . '/api/hashtagcms/public/common/v1/subscribe'),
    'external_service_timeout' => env('HASHTAGCMS_EXTERNAL_SERVICE_TIMEOUT', 5), //in seconds
    'external_config_cache_ttl' => env('HASHTAGCMS_EXTERNAL_CONFIG_CACHE_TTL', 60), //in minutes
    'external_data_cache_ttl' => env('HASHTAGCMS_EXTERNAL_DATA_CACHE_TTL', 30), //in minutes

    /** Internal Cache */
    'enable_cache' => env('HASHTAGCMS_ENABLE_CACHE', true),
    'internal_cache_prefix' => env('HASHTAGCMS_INTERNAL_CACHE_PREFIX', 'internal_'),
    'database_cache_prefix' => env('HASHTAGCMS_DATABASE_CACHE_PREFIX', 'db_'),
    'external_source_cache_prefix' => env('HASHTAGCMS_EXTERNAL_SOURCE_CACHE_PREFIX', 'ex_'),
    'cache_site_config_ttl' => env('HASHTAGCMS_CACHE_SITE_CONFIG_TTL', 30), // In minutes. Determines how often site config is loaded from DB/API. Use ?clear_cache=true to purge. 
];
