<?php

$date = date('Y-m-d H:i:s');

return [
    array('category_id' => '1','name' => '首页','title' => '首页','excerpt' => '首页摘录...','content' => '首页内容...','active_key' => 'home','third_party_mapping_key' => NULL,'b2b_mapping' => NULL,'is_external' => '0','link_relation' => NULL,'target' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_robots' => NULL,'meta_canonical' => NULL,'created_at' => $date,'updated_at' => $date,'deleted_at' => NULL),
    array('category_id' => '2','name' => '博客','title' => '查找我们最新的博客','excerpt' => NULL,'content' => NULL,'active_key' => 'blog','third_party_mapping_key' => NULL,'b2b_mapping' => NULL,'is_external' => '0','link_relation' => 'alternate','target' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_robots' => NULL,'meta_canonical' => NULL,'created_at' => $date,'updated_at' => $date,'deleted_at' => NULL),
    array('category_id' => '3','name' => '登录','title' => '登录','excerpt' => NULL,'content' => NULL,'active_key' => 'login','third_party_mapping_key' => NULL,'b2b_mapping' => NULL,'is_external' => '0','link_relation' => NULL,'target' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_robots' => NULL,'meta_canonical' => NULL,'created_at' => $date,'updated_at' => $date,'deleted_at' => NULL),
    array('category_id' => '4','name' => '注册','title' => '注册','excerpt' => NULL,'content' => NULL,'active_key' => 'register','third_party_mapping_key' => NULL,'b2b_mapping' => NULL,'is_external' => '0','link_relation' => NULL,'target' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_robots' => NULL,'meta_canonical' => NULL,'created_at' => $date,'updated_at' => $date,'deleted_at' => NULL),
    array('category_id' => '5','name' => '重置密码','title' => '重置密码','excerpt' => NULL,'content' => NULL,'active_key' => 'password','third_party_mapping_key' => NULL,'b2b_mapping' => NULL,'is_external' => '0','link_relation' => NULL,'target' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_robots' => NULL,'meta_canonical' => NULL,'created_at' => $date,'updated_at' => $date,'deleted_at' => NULL),
    array('category_id' => '6','name' => '例子','title' => '例子','excerpt' => NULL,'content' => NULL,'active_key' => 'example','third_party_mapping_key' => NULL,'b2b_mapping' => NULL,'is_external' => '0','link_relation' => NULL,'target' => NULL,'meta_title' => '例子','meta_keywords' => NULL,'meta_description' => NULL,'meta_robots' => NULL,'meta_canonical' => NULL,'created_at' => $date,'updated_at' => $date,'deleted_at' => NULL),
    array('category_id' => '7','name' => '个人资料','title' => '个人资料','excerpt' => NULL,'content' => NULL,'active_key' => 'Profile','third_party_mapping_key' => NULL,'b2b_mapping' => NULL,'is_external' => '0','link_relation' => 'alternate','target' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_robots' => NULL,'meta_canonical' => NULL,'created_at' => $date,'updated_at' => $date,'deleted_at' => NULL),
    array('category_id' => '8','name' => '联系我们','title' => '联系我们','excerpt' => NULL,'content' => NULL,'active_key' => 'contact','third_party_mapping_key' => NULL,'b2b_mapping' => NULL,'is_external' => '0','link_relation' => 'alternate','target' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_robots' => NULL,'meta_canonical' => NULL,'created_at' => $date,'updated_at' => $date,'deleted_at' => NULL),
    array('category_id' => '9','name' => '支持','title' => '支持','excerpt' => NULL,'content' => NULL,'active_key' => 'support','third_party_mapping_key' => NULL,'b2b_mapping' => NULL,'is_external' => '0','link_relation' => NULL,'target' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_robots' => NULL,'meta_canonical' => NULL,'created_at' => $date,'updated_at' => $date,'deleted_at' => NULL)
];
